### ISSUE TITLE
Can't build project 

### ISSUE THREAD

**Issue by DenzelPenzel** [yoonic/nicistore#12]
Hi, I'm trying to run you project(npm run dev) and receive an error:
Fatal error in ../deps/v8/src/api.cc, line 1051
# Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
#

==== C stack trace ===============================

    node(v8::base::debug::StackTrace::StackTrace()+0x16) [0x15c5c06]
    node(V8_Fatal+0xe8) [0x15c2d48]
    node(v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)+0x107) [0x9f2817]

Can you help me please?

**Comment by andrecrt** [comment]
What version of Node are you using? The version supported is 4.x and you can use NVM to run multiple node versions on your host.
