### ISSUE TITLE
CSS not building

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/nicistore#14]
I'm running my store against the `https://nicistore.com/v1/api` API. But seems that the page is **working** but not building.

I've cleaned cookies and other browsing histories. Tried with incognito (chrome) and safari. 

Cache-wise, I think it's something related somewhere with the code. There you go with some screenshots:
![screen shot 2017-02-27 at 9 10 55 am](https://cloud.githubusercontent.com/assets/24979743/23362563/b63a0454-fccc-11e6-8c99-89d99b6cf17f.png)
![screen shot 2017-02-27 at 9 10 47 am](https://cloud.githubusercontent.com/assets/24979743/23362566/bae2a786-fccc-11e6-8aca-8c13c5e5fb26.png)

**Comment by mateomorrison** [comment]
Similar to #3

**Comment by mateomorrison** [comment]
However, how can I make sure it loads faster [as per this](https://github.com/yoonic/nicistore/blob/master/package.json#L12). When running it to customers, speed is very important @andreftavares

**Comment by phoenixvk** [comment]
This is issue not issue. andreftavres already mentioned which url to use in Readme.md file.
