### ISSUE TITLE
Running takes too long

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/nicistore#15]
When entering `npm run dev` it get freezed on 

> webpack: Compiled successfully.

It actually takes over 30 minutes to 1 hour on a 512MB memory and 20 GB Disk running on Ubuntu 16.04.2 x64

Sometimes (like what I am experiencing now) takes forever to start, and never do nothing. What to do in this case?

**Comment by phoenixvk** [comment]
I have faced same issue. You must not use 512MB ram cause You are running nodejs App. NodeJs  require more RAM. Use 1GB RAM.

**Comment by phoenixvk** [comment]
This is not issue with atlas or nici this is issue with node. But node is also improving day by day.

**Comment by mateomorrison** [comment]
It was a RAM issue. Thanks @phoenixvk
