### ISSUE TITLE
Add Script on .js

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/nicistore#16]
I want to add the code to integrate [Customer.guru](customer.guru) the code is the following:

`<script type="text/javascript">
  window.customerguru=window.customerguru||[],customerguru.load=function(t,e){window.customerguru.client_token=t,window.customerguru.config=e=e||{};var r=e.forceSSL||"https:"===document.location.protocol,u=document.createElement("script");u.type="text/javascript",u.async=!0,u.src=(r?"https:":"http:")+"//cdn.customer.guru/embed/v1.js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(u,o);for(var c=function(t){return function(){customerguru.push(Array.prototype.slice.call(arguments,0))}},n=["schedule"],s=0;s<n.length;s++)customerguru[n[s]]=c(n[s])};
  customerguru.load("HIDDEN", { autoschedule: true, debug: true });
</script>`

When I added to [BaseHtml.js](https://github.com/yoonic/nicistore/blob/master/src/components/core/BaseHtml.js) I couldn't start the App because of a fatal error.

Where can I add it so when customers hit the website it's there?

# Crisp.im not working
[I tried integrating Crisp by adding my Website ID here ](https://github.com/yoonic/nicistore/blob/master/config/client/production.js) but seems like there is no response. No chat show up, nothing. Any add up?

**Comment by andrecrt** [comment]
You can't simply drop a script tag like that on React's render function. You can do something in the lines of what I did with Crisp (https://github.com/yoonic/nicistore/blob/master/static/vendor/crisp.js). Btw... did you also add Crips ID in this file? Should do the trick.

**Comment by mateomorrison** [comment]
Nope, not working. Added both but it showed this error:
![screen shot 2017-03-03 at 12 42 35 pm](https://cloud.githubusercontent.com/assets/24979743/23559928/03b3d77e-000f-11e7-80d0-7dd572f9be15.png)

**Comment by mateomorrison** [comment]
About Customer.Guru (and any other apps) when using their API to handle request instead of a `<script>` box, where exactly should I add the codes (I mean which files to refer).

**Comment by mateomorrison** [comment]
Did the trick when doing it with HTTPS SSL Let's Encrpt (Nginx)
