### ISSUE TITLE
Fatal error when adding image

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/nicistore#17]
When adding a product image (yes, my own RethinkDB and Atlas hosted in other server for performance purpose) the page crashed, and now it doesn't send any data. How can I add images to products without dying in the try.

It's too much to say that neither that or sending e-mail through your own server isn't specified anywhere.

**Comment by mateomorrison** [comment]
Hello @andreftavares waiting on a response

**Comment by andrecrt** [comment]
You have to inspect the logs and debug what, in your deployment scenario, may be causing that. It can be a numerous different kind of reasons, ranging from configurations, to folder permissions, to the cloud storage service you're using... Did you get it to work locally?

**Comment by mateomorrison** [comment]
@andreftavares Please don't close issues before they are resolved. This was an error when I tried adding the image:

![screen shot 2017-03-14 at 2 39 29 pm](https://cloud.githubusercontent.com/assets/24979743/23916908/14925aee-08c4-11e7-9c1b-ce5cc1578f36.png)
