### ISSUE TITLE
Fatal error when adding image

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/nicistore#21]
This is the third time that I open a issue about this, never got response or how to get it fixed. I'm trying to upload in development a image to a product or banner. It does not get uploaded no matter how many times I try or how much time I wait.

Here are some logs that got printed when I tried adding them:
![screen shot 2017-03-14 at 2 39 29 pm](https://cloud.githubusercontent.com/assets/24979743/23930537/561a615c-0903-11e7-9e7d-fb5d6b1b1dc8.png)

I have not modified any route, Atlas is running perfectly and RethinkDB is running too. We've been trying to hack it out for days now but can't understand the code or how it's handling the requests. Hopefully waiting someone steps in and help me fix this.

**Please DO NOT close this issue without solving, responding or providing useful solution 💯 **

UPDATE: There is JWT key and everything is running smoothly. So that may not be the problem.

**Comment by andrecrt** [comment]
Hi,

1. That log is from Atlas, this repo is for Nicistore.
2. The stack trace is related to [this](https://github.com/yoonic/atlas/blob/master/src/resources/contents/serializers.js#L42), which has nothing to do with uploads, nor products.
3. This is a personal project that I opted to open-source and that I'm glad to support as time permits. As it is said in the [licence](https://github.com/yoonic/nicistore/blob/master/LICENCE) "THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND".
4. "can't understand the code or how it's handling the requests":
    - https://github.com/yoonic/atlas/blob/master/src/resources/files/routes.js#L13-L39
    - https://github.com/yoonic/atlas/blob/master/src/resources/files/handlers.js#L16-L32
    - https://github.com/yoonic/atlas/blob/master/src/resources/files/utils.js#L17-L50
5. If you follow the READMEs on both projects you should get everything working and I believe the code for uploads is pretty straightforward, even if you want to extend it (e.g. to support AWS S3).

Best regards,
André.

**Comment by mateomorrison** [comment]
Hello André, thanks for the response. 

I believe we can all cooperate with the open-source with a great community to make it better. I've done all in the READMEs but still not able to upload images.

**Comment by rockneverdies55** [comment]
@mateomorrison - make sure you created `uploads/` folder with the correct **subfolders** (e.g. `products` for uploading images for Products) under the root of atlas project.
