### ISSUE TITLE
cant set up the project

### ISSUE THREAD

**Issue by estebanmuruzabal** [yoonic/nicistore#22]
65% building modules 738/797 modules 59 active ...de_modules/react/lib/ReactFragment.jserror: Failed connecting to MongoDB no hostname or hostnames provided in connection string
info: Server start at http://127.0.0.1:3000
 64% building modules 923/1012 modules 89 active ...refixer/lib/utils/unprefixProperty.js[nodemon] app crashed - waiting for file changes before starting...

I would very much appreciate if you have an idea why I am having this error. Am I supposed to have mongodb running? 

cheers!!

**Comment by mateomorrison** [comment]
If you follow the ReadME it should get running. But this doesn't look good.

* Nicistore is built on RethinkDB. **not** MongoDB
* DataBase has nothing to do with the storefront. You can run it against nicistore's API.

**Comment by estebanmuruzabal** [comment]
somehow I fixed. and had some sass problems but solved it upgrading to "node-sass": "^4.5.0"! 

Sorry for bothering! Thanks for sharing the code, looks amazing
