### ISSUE TITLE
Any interest in picking this up?

### ISSUE THREAD

**Issue by mateomorrison** [yoonic/nicistore#41]
Hello guys!  I will be soon forking this project to keep it maintained (upgrading the dependencies, integrate Stripe, and updated admin panel). Is someone else interested?

**Comment by Max7St** [comment]
Hi @mateomorrison , yes, it would be great

**Comment by petroved** [comment]
hi @mateomorrison, if you are interested you could take a look on my fork of this library https://github.com/petroved/simple-store It's already have some dependency updates and improvements. Feel free to use it as boilerplate or ask me any questions about it.

**Comment by mateomorrison** [comment]
Hi, @petroved. Thank you! I will keep you in the loop about this.

Edit: As we found some interest, we will start working on this from [https://github.com/gofangoo](url) and I will start to get our team to fully support this. Closed.
