### ISSUE TITLE
Needs an explanation of default business rules/data structures

### ISSUE THREAD

**Issue by Redmega** [yoonic/nicistore#5]
For example, the difference between a Collection and a Category. Would it be like, Category is "Apparel" and collection is "Spring"? Is collection a member of category, or are they independent? etc.

**Comment by andrecrt** [comment]
The storefront is powered by the Atlas API and its only business rule/data structure for grouping products is "Collections". 

It's up to the storefront consuming the API to create any additional logic. In this case, the logic of "Categories" and "Collections" (this time around in the sense of "Spring", "Summer", etc).

The way this logic is embedded in the API/Database is through the property `tags` of the Collections resource. If you browse the [Live API](https://nicistore.com/api/v1/collections) you can see that there are API Collections with the tag `category` and the tag `collection`. This is where the storefront looks for to see if the API Collection is a Category or a Collection.

Hope this makes sense :)
